# Global config
global:
  scrape_interval: 30s
  # evaluation_interval: set to 1m as default
  # scrape_timeout: is set to the global default (10s).

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node_exporter
    static_configs:
      - targets: ['192.168.1.16:9100'] 
  - job_name: snmp_exporter
    static_configs:
      - targets: ['192.168.1.2']
    metrics_path: /snmp
    params:
      module: [synology]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9116
